### ISSUE TITLE
[transmogrification] new hair styles are not available 

### ISSUE THREAD

**Issue by voguelike** [Hydrox6/external-plugins#105]
This issue is for the external plugin: {transmogrification}
Plugin version: {1.3.5}

~~if you use one of the new hair styles, in my case the high ponytail, enabling the transmog will change it to another hairstyle which for me seems to be the previous one.~~
~~clearing the hair slot doesn't do anything and the use base option hairstyle just makes it use the other hairstyle that is no longer on my character or in the transmog.~~

removing and reinstalling the plugin did not work and neither did deleting all the presets.

turns out i had a corrupted preset, which reinstalling didn't get rid of and it was impossible to delete. after manually going through the runelite files and removing all of the transmogrification entries the plugin reset to it's initial state.

i'll leave this up for anyone who runs into the same problem and to ask for support for the new hairstyles.

**Comment by Enriath** [comment]
Part of the original design goal for this plugin was for it to be 0 maintenance, so if I ever stopped playing the game, it would survive without me. Hair was something that could not be automatically pulled, sadly. I'm amazed at how many game updates have passed with no issues, to be honest.

Looking at the new hairstyles (in the fancy new interface, nice one Jagex!), it seems that most (if not all) of them are hairstyles that used to be locked to the other gender (again, nice one Jagex!). Luckily, I can quite easily get the data needed for the plugin to work, it'll just take some time and data entry. Plus, with the new display models used in the interface, I can update how the icon search looks to be more slick and less... haunting.

Thank you for raising the issue. I'm not sure why your preset got corrupted, but at least I can add the new hairs in. Should have it done within a couple of days, plus however long it takes the RuneLite lot to review and merge it.

**Comment by Enriath** [comment]
Ok, I lied: the update is already done and submitted (after an issue with a badly communicated API change on RuneLite's end). It'll be v1.3.6.

If you're in the server, keep an eye out in the `#github` channel for the merge commit, otherwise just keep an eye out for the updated version in the client.

**Comment by Enriath** [comment]
v1.3.6 has been added to the hub.
