### ISSUE TITLE
trailblazer clues

### ISSUE THREAD

**Issue by Devdeve** [Hydrox6/external-plugins#11]
This issue is for the external plugin: trailblazer clues
![image](https://user-images.githubusercontent.com/18165565/98549919-58c87080-2293-11eb-8d5a-880473503ce4.png)
The plugin is saying that it is completable, you need the evil dave miniquest in RFD to be able to access evil dave's basement.
You need desert for a pre-requisite quest so it is currently uncompletable without it.

**Comment by Hydrox6** [comment]
Ah, good spot. Didn't realise that you needed it for the basement. I'll get that into v1.1.1

**Comment by Hydrox6** [comment]
It's in the client now. Restart or go to the plugin hub and update it from there
