### ISSUE TITLE
Map clues not showing region requirements

### ISSUE THREAD

**Issue by weiyih** [Hydrox6/external-plugins#12]
![unknown](https://user-images.githubusercontent.com/18219349/98606415-3e06f380-22b5-11eb-8dfb-a630de9d84e0.png)
Medium clue scroll
Location: North of the Tower of Life map clue
Region: Kandarin Region 
ItemID: 3599

**Comment by Hydrox6** [comment]
I'm not sure how this happened. I've tested the map detection code and it's working fine, even on v1.1.2. I'll be moving some stuff around to hopefully make it more robust, but that's weird. Any chance you could upload your `client` log? Instructions can be found at the top of [here](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client)

**Comment by Hydrox6** [comment]
nevermind, I just figured it out. I'm a giant idiot, and it'll be in 1.2 later today
