### ISSUE TITLE
[Attack Styles] Blue Moon Spear does not properly hide styles

### ISSUE THREAD

**Issue by PureIllenium** [Hydrox6/external-plugins#123]
This issue is for the external plugin: Attack Styles
Plugin version: Not able to find as the plugin appears to be built in.

When using the Blue Moon Spear, the styles do not update properly when hiding them in the plugin. The defensive casting does hide with defence hidden and warning for but not the other styles.

![Attack Styles Blue Moon](https://github.com/user-attachments/assets/bfa37e30-9459-44b1-a96f-0b536cb0e13c)

**Comment by Enriath** [comment]
I have nothing to do with the Attack Styles plugin. Report this to the core RuneLite repo

**Comment by PureIllenium** [comment]
Oh sorry, I was in the wrong repo
