### ISSUE TITLE
[Trailblazer Clues] Hard Step is classified as Asgarnia instead of Misthalin in error

### ISSUE THREAD

**Issue by Marstead** [Hydrox6/external-plugins#16]
This issue is for the external plugin: {Trailblazer Clues}

The hard step "Talk to Sir Prysin in Varrock Palace" is mistakenly classified as an Asgarnia clue. While most of the White Knights are in fact in Falador, Sir Prysin is in Varrock and so this should be classified as a Misthalin clue.

**Comment by Hydrox6** [comment]
Good shout, not sure what happened here. Will be in v1.4.1
