### ISSUE TITLE
[Trailblazer Clue] Plugin specifies Wilderness as requirement, which is false

### ISSUE THREAD

**Issue by MunsterMc** [Hydrox6/external-plugins#17]
Wilderness Capes can be obtained from Richard in Edgeville, which is in Misthalin. Clue step does not require Wilderness to complete.
![image](https://user-images.githubusercontent.com/30962666/99722044-5a264400-2ab0-11eb-81c3-8eb0c6f0f8fd.png)

**Comment by Elite386** [comment]
Also for this clue.
![image](https://user-images.githubusercontent.com/67659871/99760596-ac1f9780-2ab9-11eb-9b04-f337b60cb6f3.png)

**Comment by Hydrox6** [comment]
Knew I should have checked the issues before I did v1.4. Also not sure how I forgot about Richard
