### ISSUE TITLE
[Trailblazer Clues] Console spammed with warnings when shop/bank interfaces are open

### ISSUE THREAD

**Issue by ShaunDreclin** [Hydrox6/external-plugins#18]
This issue is for the external plugin: Trailblazer Clues

```
2020-11-20 10:55:22 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException: 1
	at io.hydrox.trailblazerclues.TrailblazerCluesOverlay.render(TrailblazerCluesOverlay.java:111)
```

**Comment by Hydrox6** [comment]
I fixed this in an update 8 days ago. You should really close your client sometime

**Comment by ShaunDreclin** [comment]
Update's not getting pushed out then for some reason cause I close my client multiple times a day lol

**Comment by Hydrox6** [comment]
When running a dev client, it's on *you* to keep it up to date, including the hub. You really need to update your plugin hub

**Comment by ShaunDreclin** [comment]
Ah, I see where I made a mistake. Thought I had the hub auto-updating everywhere but missed one of my shortcuts. Sorry about that!
