### ISSUE TITLE
[Trailblazer Clues] Clue steps which need a team cape can be completed without the Wilderness area

### ISSUE THREAD

**Issue by HarveyPeachey** [Hydrox6/external-plugins#19]
This issue is for the external plugin: {Trailblazer Clues}

I've just completed a Medium clue step in castle wars which requires a team cape and it said I wouldn't be able to complete it. You can get a team cape as a reward from Easy clue caskets.

**Comment by HarveyPeachey** [comment]
Example: 
![2020-11-22_12-41-02](https://user-images.githubusercontent.com/4706195/99904059-81536000-2cc0-11eb-8e23-1b4e42b8f86b.png)
![2020-11-22_12-41-18](https://user-images.githubusercontent.com/4706195/99904061-857f7d80-2cc0-11eb-9ee2-c8b41e2ceee1.png)

**Comment by Hydrox6** [comment]
Duplicate of #17
