### ISSUE TITLE
Hide/show specific items

### ISSUE THREAD

**Issue by yani** [Hydrox6/external-plugins#2]
This issue is for the external plugin: inventory-summary

It would be interesting to have a black-/white list for specific items.
That way only loot and stuff like farming supplies can be shown, instead of switchables, runes, teletabs, etc.

**Comment by Hydrox6** [comment]
Added in 73899cf02c12abc21f12f9af073ff6452fdbcf06 (would have been #36 if I didn't screw up the commit :d )
