### ISSUE TITLE
[Trailblazer Clues] Karamja Ship Yard clue step requires Kandarin

### ISSUE THREAD

**Issue by emerald000** [Hydrox6/external-plugins#20]
This issue is for the external plugin: Trailblazer Clues

The clue "04 degrees 16 minutes south 16 degrees 16 minutes east" requires Kandarin. The Ship Yard requires part of The Grand Tree to enter, which is only possible if you unlock Kandarin.

**Comment by Hydrox6** [comment]
Good spot, forgot this had a quest req
