### ISSUE TITLE
[Trailblazer Clues] Clue requirements shown only after relaunching client

### ISSUE THREAD

**Issue by slayer621** [Hydrox6/external-plugins#23]
This issue is for the external plugin: Trailblazer Clues
I was minnow fishing and got this clue from a medium clue bottle. No requirements were listed on the clue initially. I tried dropping it and picking it back up to reset as well as relogging but the Trailblazer requirements were still missing. 

I was typing this issue up but decided I should relaunch Runelite just in case. After relaunching, the requirements appeared. If I'm able to somehow reproduce this, I'll update this issue. For now, I'm just posting for reference.

![0kDf0](https://user-images.githubusercontent.com/9104303/100522784-14810f80-3171-11eb-82b6-dc996ca0bd19.png)

Some other info that might possible be useful:
- I initially logged in on the minnow platform and was minnow fishing for the duration on the report button on the screenshot.
- I did not leave the minnow platform 
- My inventory layout did not change (was only fishing and reading on other monitor)
- The clue bottle sat in my inventory for like 15 minutes because I didn't want to take a break to open it
- Other active plugin hub plugins, just in case: Annoyance Mute, Bank Tag Generation, Banked Experience, Death Indicator, Equipment Inspector, Essence Pouch, Examine Tooltip, Fight Cave Waves, Gnome Restaurant, Hydrate reminder, Inventory Setups, Last Recall, Left Click Dropper, Magic Secateurs, Menu Swapper Extended, OSRS Wiki Crowdsourcing, Patch Payment, Profiles, Quest Helper, Resource packs, Spec Regen Timer, Supplies Tracker, Time to Level, Trailblazer Clues, Zulrah Plugin

**Comment by Hydrox6** [comment]
You'll have to upload your client log from when that happened, not sure what would be causing that. You're not the first to report it though

**Comment by slayer621** [comment]
Here's the log from that day. It was sometime between 11am and 12:16pm, for reference. [client_2020-11-28.0.log](https://github.com/Hydrox6/external-plugins/files/5626146/client_2020-11-28.0.log)

(side note, that hydrate reminder is way too chatty in the logs. Going to remove that)

**Comment by Hydrox6** [comment]
Nothing off in there at all, so everything is "working". I really don't know what it could be, unless I manage to repro it myself. Sorry about that

Also, jfc that really is spammy

**Comment by slayer621** [comment]
No worries. If I get another clue, I'll also try to reproduce for a bit as well. I've been using the plugin for a while and that was the only issue so far and it hasn't happened since, so I'm honestly not worried. If I discover anything, I'll post it here.

**Comment by slayer621** [comment]
Oddly enough, it happened again about 20 minutes ago. This time with a birds nest. I wasn't able to reliably repro it nor make it work in any way other than restarting my client, but I do see this log at least has some errors in it, though none from this plugin. I want to say the nest dropped at about 9:15 PM, or shortly after the 2020-12-02 21:11:16 timestamps. 2020-12-02 21:37:13 is when I restarted my client. 
[client.log](https://github.com/Hydrox6/external-plugins/files/5633528/client.log)

**Comment by jackemerson** [comment]
I seem to encounter the issue whilst using either Classic Layout, Resizeable or Fixed. Switching to Modern Layout allows me to reliably see the requirements (though I've not tested this extensively).

It may also tie into the Runelite client size? Perhaps to do with how the text is anchored/positioned, with different layouts shifting it off-screen.

**Comment by Hydrox6** [comment]
So when you said Classic layout, I thought I hadn't done support for them, but the real issue was weirder. If you've loaded up the other style (Modern or Classic), those widgets will stay in the client, and just get hidden. They're a completely separate widget tree, which is odd that they'd stay. The check at the moment will cascade through each of the 3 styles, breaking on the first one it finds. If it finds the hidden one, it just won't show.

I'll be pushing an update today that will fix it, hopefully it won't take too long to get accepted
