### ISSUE TITLE
[Trailblazer Clues] Incorrect area requirements

### ISSUE THREAD

**Issue by WombaTharrier** [Hydrox6/external-plugins#24]
This issue is for the external plugin: Trailblazer Clues
The clue "Where safe to speak, the man who offers the pouch of smaller size wishes to see you alignment" incorrectly states that it can be completed with only Misthalin. For the clue, you have to speak with the Mage of Zamorak wearing 3 Zamorakian items in Varrock. However, he doesn't spawn in Varrock without starting the Enter the Abyss miniquest. That means you would have to have wilderness to finish this step. 
![image](https://user-images.githubusercontent.com/75311496/100736781-d8c88e80-3398-11eb-8136-a97677ac4ca5.png)

**Comment by Hydrox6** [comment]
Ah, didn't realise he required the miniquest. ty for the report
