### ISSUE TITLE
[Transmog] Message spam

### ISSUE THREAD

**Issue by MESLewis** [Hydrox6/external-plugins#27]
This issue is for the external plugin: Transmogrification
![image](https://user-images.githubusercontent.com/597053/105778854-715b3500-5f2a-11eb-9dd6-229e88e392b4.png)
This message triggers repeatedly forever upon clicking "Enable Transmogrification". The message stops when clicking "Save as Default State"

**Comment by Hydrox6** [comment]
This should be fixed in v1.0.2
