### ISSUE TITLE
[Transmogrification] Prospector helmet does not show hair and face

### ISSUE THREAD

**Issue by nickyGyul** [Hydrox6/external-plugins#31]
This issue is for the external plugin: Transmogrification

The player's face and default hair disappears when using head slot items that use the player's default hair.
The most notable head slot items are:
- Angler hat
- Prospector helmet
- Farmer's strawhat

[Transmog enabled](https://i.imgur.com/ZkfqQJ8.png) vs [Transmog disabled](https://i.imgur.com/Rp93ozw.png)

I wonder if having an option to Reset the plugin's configuration might help with the disappearing head issue. Thanks in advance! I love this plugin and how polished it is.

**Comment by Hydrox6** [comment]
if you're wearing a helmet, your head gets hidden. this is why there are options to change you hair, jaw, and sleeve slots. I'm 90% sure I mention this in the help section

**Comment by nickyGyul** [comment]
Oh now I understand what you mean by default state. The "How to use" section was pretty unclear on what the Default state was. I ended up not setting it up correctly because the in game `?` instructions didn't even mention what to set your default state. Other friends had a similar issue.

In the "How to use" section could you add: "If your head is hidden when the transmog is enabled, make sure your default state includes your hair and/or sleeves. Otherwise, you will have your head hidden when wearing certain head slot items."

I accidently set my default state wearing full graceful which ended up [breaking the jaw and hair options](https://i.imgur.com/FC3nTm2.png) so I wasn't able to change them per the instructions.

This would clear up any confusion for idiots like me. Again, tysm for the plugin.

**Comment by Hydrox6** [comment]
When you initially get the plugin, the entire UI is blocked off and it tells you to remove all your armour and then set your default state. I can't make it any more clear than that unless I specifically block the button as well unless you're wearing nothing, which wouldn't be a bad change imo.
