### ISSUE TITLE
[transmog] add toggle to allow transmogrification in wilderness

### ISSUE THREAD

**Issue by knobbyknob** [Hydrox6/external-plugins#33]
This issue is for the external plugin: {transmog plugin}

It would be nice to look beautiful in the wilderness as well.  Is there any particular reason it is disallowed entirely?  If not, could you please add this functionality?

Thanks

**Comment by Hydrox6** [comment]
I noted this in my initial release on the plugin-hub PR.

> One point of note is that it is disabled in PvP situations. This is due to being based on the ideas of the RS3 customisation systems. There it's disabled since the data is shared across clients, and while it would be very nice to eventually maybe get that in the plugin, with PvP having a big emphasis on gear switching, I wanted to make sure that in the (hopefully) rare case that this broke, it wouldn't negatively affect people not being able to see their own switches at a glance.
