### ISSUE TITLE
[tmog] Add pet tmogs, and weapons but only for matching animations

### ISSUE THREAD

**Issue by Bamboozaler** [Hydrox6/external-plugins#37]
Just want to let you know you single handedly added the best plug-in to runelite. If you have a donation page let me know.

One suggestion I would add is add t-mog to pets and matching weapon styles. I know it might be a lot of work, but that's the only big feature this plug-in is missing. If the weapon style animation mog is just too much work it's completely understandable why you wouldn't add it.

Adding t-mog to pets would definitely make the game more fun. Again, great work!

**Comment by Hydrox6** [comment]
Thanks! Donation button is at the top right of the page, GitHub calls it "Sponsor", even though it just links to PayPal

As for weapons, yeah it's entirely an animation thing. There's really not a way to do it without hardcoding everything atm, and that's just really not good: I'm trying to avoid having to baby this plugin every time Jagex adds something new. RS3's system (which is what this is based on) is even worse, where the override you pick only shows if you've got a weapon of the same type, which is even more nightmare to the issue.

As for pets, they're similarly difficult but for different reasons. They're also not armour so they've never really counted for this, and it's not something I ever want to do.
