### ISSUE TITLE
[Transmog] Male versions of armour for Females

### ISSUE THREAD

**Issue by septicsalmon** [Hydrox6/external-plugins#41]
This issue is for the external plugin: Transmog
Would it be possible to offer the male versions of armour such as d'hide bodies, wizard robes ect?
For people who dont like the "crop top" look that female armour has.

**Comment by septicsalmon** [comment]
I suppose you could offer the opposite for male characters who would like to dress up in the more "female" version of clothing. Each to their own

**Comment by Hydrox6** [comment]
Sadly no. The models are basically what you see, including the proportions of the body for that gender. 

And even if I wanted to make women look like [Kanye](https://i.ibb.co/Xk7tDLY/kanye-i-love-it.webp) with their male armour forms, the kits don't even work on models, they work off of essentially item IDs; what determines the model used is buried deep in the client, further than a hub plugin can reach.

**Comment by septicsalmon** [comment]
thats a shame! thanks for the swift response
