### ISSUE TITLE
[Transmog] Some items named "Members Object".

### ISSUE THREAD

**Issue by DuhonTheGuy** [Hydrox6/external-plugins#43]
This issue is for the external plugin: Transmog

Most of the items in the plugin are just called "Members Object", maybe because I am f2p? Problem is as follows:

![Selection_023](https://user-images.githubusercontent.com/53868103/120049158-24c25c00-bfe7-11eb-811d-5d54155e61a1.png)

**Comment by Hydrox6** [comment]
Yeah that's because of how the client loads items. This isn't really something I can fix without an insane amount of extra effort on this plugin, and it would add a tonne of fragility I really don't want to have to constantly deal with
