### ISSUE TITLE
[Transmogrification] missing graceful colours 

### ISSUE THREAD

**Issue by dusty-dusty** [Hydrox6/external-plugins#44]
There is two missing colours, Hallowed Sepulchre( black ) and Trailblazer League ( brown )

**Comment by Hydrox6** [comment]
Both of those are present for me now. I have a sneaking suspicion that's thanks to a recent wiki data update in the client; there might have been an issue scraping it before.

In general, items being missing is not really an issue of my plugin, as I get the data from the base client's item stats list.
