### ISSUE TITLE
[Contextual Cursor] override default OS cursor

### ISSUE THREAD

**Issue by Bram91** [Hydrox6/external-plugins#5]
This issue is for the external plugin: Contextual Cursor

An option to override the default OS cursor with a more fitting one. Currently the plugin only overrides on interaction options, so it keeps changing between my windows cursor and a contextual one.
The `Rs3 Gold` cursor from the `Custom Cursor` plugin might fit better.

**Comment by Hydrox6** [comment]
Custom Cursor support was added in 1.2
