### ISSUE TITLE
[Transmog] option to restrict transmogging only to items you own in bank or poh storage

### ISSUE THREAD

**Issue by septicsalmon** [Hydrox6/external-plugins#57]
This issue is for the external plugin: Transmog

Could you add an option that only allows or shows items in that you currently have in you bank? It's currently OK to self impose this restriction but it gets a bit difficult to remember what you own spread over bank and poh

**Comment by Hydrox6** [comment]
I'm really not keen on the idea of storing the player's bank and PoH storage in the config; there's already enough data from this plugin as is.
