### ISSUE TITLE
[Shattered Relic XP] Suggestion: Time to level relic

### ISSUE THREAD

**Issue by PythonMeat** [Hydrox6/external-plugins#69]
This **Suggestion** is for the external plugin: Shattered Relic XP

A TTL would be very handy in the hover of the fragments.

TTL would be easily calculated since you get xp every 4t or 2.4s

(8000 - CurrenXP) * 2.4 * 60 = TTL in min

**Comment by Hydrox6** [comment]
This would be quite a lot of complexity for not much gain. Given the short length of the league, this really isn't worth it.
