### ISSUE TITLE
[Shattered Relic XP] Feature request: Dynamically update xp tooltip

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Hydrox6/external-plugins#71]
This issue is for the external plugin: Shattered Relic XP
Plugin version: 1.4

When hovering over a relic fragment icon on the buff bar, the XP bar doesn't update until the mouse is moved off and back on. I would like this tooltip to dynamically update when new relic XP is earned.

Redrawing the tooltip every game tick might work.

**Comment by Enriath** [comment]
The code is only ran when the tooltip is built. Running it every frame is not only more costly, but more complicated to have work correctly, plus it's also very wasteful.

Besides, if you want a live update of your relic progress, use the overlay options.
