### ISSUE TITLE
[Shattered Relics XP] Descriptive descriptions don't work with progress bar and xp turned off

### ISSUE THREAD

**Issue by Keilo104** [Hydrox6/external-plugins#75]
This issue is for the external plugin: Shattered Relics XP
Plugin version: 1.7

The option "Descriptive Descriptions" under "Tooltip" only works if you have either "Show Progress Bar" or "Show XP" (or both) active, and doesn't work if you have both turned off.

**Comment by Enriath** [comment]
ah good catch, forgot to include it in a function

**Comment by Enriath** [comment]
Fixed in 1.8
