### ISSUE TITLE
[Shattered Relics XP] Fragment description and XP amount isn't accurate when missing fragments on loadout

### ISSUE THREAD

**Issue by Keilo104** [Hydrox6/external-plugins#77]
This issue is for the external plugin: Shattered Relics XP
Plugin version: 1.7

When missing fragments on loadout, some fragments might end up having the descriptions and XP amount of other fragments. I suspect this happens because of using indexes and expecting the player to always have a full loadout.

**Comment by Enriath** [comment]
This would be more of a pain to fix than it's worth. There's really no situation in which the player shouldn't have all relic slots filled.
