### ISSUE TITLE
[Shattered Relic XP] Certain configuration of Relics shows incorrect set effect overlay for chain magic

### ISSUE THREAD

**Issue by pwatts6060** [Hydrox6/external-plugins#78]
This issue is for the external plugin: Shattered Relic XP
Plugin version: 1.8
![image](https://user-images.githubusercontent.com/30028569/153320144-0a5a1112-9ad0-49aa-93dc-a82af5025cc4.png)
![image](https://user-images.githubusercontent.com/30028569/153320158-960bcca9-186c-46ce-922f-2f1142421c7f.png)
Unholy Wizard - Chain Magic
Arcane Conduit
Praying Respects
Imcando's Apprentice - Chain Magic
Alchemaniac
Mother's Magic Fossils - Chain Magic 
The overlay is showing it's only 2 fragments but I have 3)

**Comment by pwatts6060** [comment]
The issue is in SetEffect.java. Imcando Apprentice is not in the enum but should be there.
`CHAIN_MAGIC("Chain Magic",
		new Effect[]{
			new Effect(2, "30% chance to hit twice with Magic"),
			new Effect(3, "60% chance to hit twice with Magic")},
		THRALL_DAMAGE, UNHOLY_WIZARD, ZAMORAKIAN_SIGHT, MOTHERS_MAGIC_FOSSILS, DEEPER_POCKETS, ROOTY_TOOTY_2X_RUNEYS, HOT_ON_THE_TRAIL),`

**Comment by Enriath** [comment]
Fixed in 1.11
