### ISSUE TITLE
[Contextual Cursor]

### ISSUE THREAD

**Issue by knrs95** [Hydrox6/external-plugins#8]
This issue is for the external plugin: Contextual Cursor

Wanted to say I love this plugin, no issues I've come across and I'll keep an eye for any in game menus that could use a cursor update. But, I did have an idea for a plugin that you might be interested, it's in the same vein as this plugin. I don't know if you remember the loot beams from RSHD but I always thought those were cool and increased that sweet dopamine hit. Would you ever have interest in making a plugin similar?

**Comment by Hydrox6** [comment]
Loot beams are not possible as an external, due to major internal changes. Trevor has been looking to make them for a long time now.
