### ISSUE TITLE
[Shattered Relic XP v1.12] 'Override buff bar limit' no longer works.

### ISSUE THREAD

**Issue by Spongled** [Hydrox6/external-plugins#80]
This issue is for the external plugin: Shattered Relic XP
Plugin version: v1.12

The 'Override buff bar limit' option within the plugin no longer works, only 8 icons can be displayed (7 relics + 1 set effect), even when the option is enabled. I believe this issue begun with the latest game update.

**Comment by Enriath** [comment]
The option has only existed *since* the last game update, and it definitely works. You're going to have to be more specific, provide repro steps and whatnot

**Comment by Spongled** [comment]
Apologies, wasn't aware. 

As for repro steps - it's as simple as equiping 7 relics. It will only ever display a maximum of 8 icons on my end. 

I've tried toggling the option, as well as reinstalling the entire plugin, restarting the client - no dice. Let me know if there's anything else you'd like me to try.

**Comment by Enriath** [comment]
Unable to reproduce; as I already said, it definitely works, even tried it with a forced 7
![image](https://user-images.githubusercontent.com/2979691/155856473-20b96b8c-90ba-4a7f-9d43-717d250c40f2.png)

**Comment by Spongled** [comment]
Odd - I haven't been able to get it to work. I'm assuming something changed within the display mechanism if this was an option you added within the last update? As that's when I was no longer able to view above 8 icons. It hasn't worked with any relic combination I've tried post-update.
![1 (1)](https://user-images.githubusercontent.com/27869072/155856616-baa60938-235c-4724-80c8-de728bbff45e.png)
![1 (2)](https://user-images.githubusercontent.com/27869072/155856617-21977e64-fc88-4784-9f3c-ba888513a0fe.png)


Edit -

Just to add: the 'Display Fragments' toggle within the in-game Leagues interface no longer works either. I'm unable to turn the display off. I'm wondering if this is a related issue?

**Comment by Enriath** [comment]
Ah that's why: you're a cheater.

Be gone, I don't support cheaters
