### ISSUE TITLE
[Inventory Summary] Add ability to hide when there are no whitelisted items in the inventory

### ISSUE THREAD

**Issue by asherbasher** [Hydrox6/external-plugins#85]
This issue is for the external plugin: Inventory Summary
Plugin version: 1.2.1

Add the ability to hide the plugin when there are no whitelisted items in the inventory. Currently I just toggle the plugin on and off but would prefer if this was an option.

**Comment by Enriath** [comment]
I have a feeling this would cause more confusion than anything

**Comment by asherbasher** [comment]
Ok, no problem.

**Comment by ste-h** [comment]
I was wondering if you would reconsider this, as I had the exact same request.

I think so long as it's off by default, there wouldn't be any confusion
