### ISSUE TITLE
[Contextual Cursor] Resizing of infobox groups

### ISSUE THREAD

**Issue by Bram91** [Hydrox6/external-plugins#9]
This issue is for the external plugin: Contextual Cursor

When trying to resize infobox groups when the Contextual Cursor plugin is enabled the arrow cursor appears for 1 client tick and then resets back to default, preventing the user from resizing infobox groups:
![infobox-resizing](https://user-images.githubusercontent.com/7499230/94782761-fb0b5380-03cb-11eb-983e-324bea6b1983.gif)

**Comment by Hydrox6** [comment]
Fixed in 1.2
