### ISSUE TITLE
[Contextual Cursor] Cursor is not displaying in front of menus

### ISSUE THREAD

**Issue by dudeyourajerk** [Hydrox6/external-plugins#90]
This issue is for the external plugin: {contextual cursor}
Plugin version: {latest}
The custom cursor started appearing behind menus. It still reacts to the action just is not displaying in front of the text/menus any longer.
![issue](https://user-images.githubusercontent.com/111164032/185720747-29d48ec0-7682-467f-bd71-dacc40853951.png)

You can see in the picture, the issue im describing. Have already tried uninstalling and reinstalling to no help.

**Comment by Enriath** [comment]
This has been fixed in v1.3.1 which is awaiting review

`latest` is also not a valid version for bug reports
