### ISSUE TITLE
[inventory-summary] Opacity on hover

### ISSUE THREAD

**Issue by najawa** [Hydrox6/external-plugins#94]
This issue is for the external plugin: inventory-summary
Plugin version: 1.2.1

Sometimes I click on a potion in the inventory summary, because it looks exactly the same as my inventory. This causes my character to start walking, which can be extremely fatal in some situations. It would be really nice if there was an option to enable the summary going transparent onmousehover so that if I try to click on something, there's some feedback that I'm not looking at a usable backpack/inventory

**Comment by Enriath** [comment]
I'm reasonably sure that any unstackable item looks entirely different in the Inventory Summary overlay, as I always force the quantity to show as if the item were stackable. This sounds like more of a potential issue with the core `Inventory Viewer` plugin.
