### ISSUE TITLE
[Contextual Cursor] Option to replace default cursor

### ISSUE THREAD

**Issue by lottieratworld** [Hydrox6/external-plugins#96]
This issue is for the external plugin: Contextual Cursor
Plugin version: 1.3.1

On Linux, the default Custom Cursor plugin doesnt accurately show the RS3 Gold cursor which I presume the cursors in this plugin are themed after (see [this issue](https://github.com/runelite/runelite/issues/8731)), while this plugin DOES show the contextual cursors in full color. Along with that, the cursor in Contextual Cursor scales up with the interface scale when using the Stretched Mode plugin, while the default/custom cursor does not. For that reason I would love to have the option to have this plugin skin the default cursor (when not hovering over interactables) as well using the same overlay system.

Images below show the inconsistency between the default custom cursor and this plugin's cursors, at least how it looks on Linux. The ui (and in turn the contextual cursors) is scaled up with Stretched Mode.
![cursor1](https://user-images.githubusercontent.com/51107143/205597580-69fbb72d-3d12-4073-9edf-51bff0218b02.png)
![cursor2](https://user-images.githubusercontent.com/51107143/205597620-c4687f33-683b-44b1-b790-6c0b79facc21.png)

**Comment by Enriath** [comment]
Contextual Cursors works by using a RuneLite overlay to display the icons, allowing it to work cross platform (while Java's cursor support is lacking), and allowing it naturally scale with the UI. The tradeoff is that it's not perfectly accurate; the tracking of the mouse is very slightly laggy, which can manifest if a user has bad performance; it has happened in the past that the tracking of whether a contextual cursor is being shown has caused the mouse to entirely disappear, which would *really* be not good if that cursor was the default cursor; and generally, users have shown a disinterest in overly large UI elements on Fixed mode in the past, so making the cursor big as well sounds like a bad idea.

I'm also personally not keen on re-implementing a core plugin, especially not with those issues above. Custom Cursors only working on Windows is really a core RuneLite issue, which in turn stems from the terrible cursor support that Java has that I alluded to above.

**Comment by lottieratworld** [comment]
fair enough! it was mostly the inconsistency between the default and contextual cursors bothering me so at least having an option to turn it on would be nice, though i understand not wanting to implement it given your reasons. feel free to close this issue if youre not interested in adding this option.
