### ISSUE TITLE
[Plank Sack Plugin] Plank Sack Plugin causing runelite crash?

### ISSUE THREAD

**Issue by SandroVA** [Hydrox6/external-plugins#98]
So my runelite just crashed. I checked the runelite logs and I see that the last thing logged was the plank sack plugin remove info box. 
[client.log](https://github.com/Enriath/external-plugins/files/10679855/client.log)
[launcher.log](https://github.com/Enriath/external-plugins/files/10679856/launcher.log)

(Crash happened at around 5:08pmish)

**Comment by Enriath** [comment]
Whatever caused the crash tends not to get logged, as the crash breaks the logging system as well. An NPE in a RuneLite system tends not to cause the entire client to break; it's more likely that some form of GPU-related issue is afoot, which has nothing to do with any of my plugins
